---
fixtures:
  repositories:
    "concat":
        repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
        ref: '4.2.0'
    "stdlib":
        repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    "libvirt": "#{source_dir}"
