---
sudo: false
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
rvm:
        - 1.9.3
        - 2.1.0
script: bundle exec rake test
env:
        - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
        - PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes

matrix:
        exclude:
                - rvm: 1.9.3
                  env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
                - rvm: 1.9.3
                  env: PUPPET_GEM_VERSION="~> 5.0" STRICT_VARIABLES=yes
