# nwfilter rule protocol of IGMP, ESP, AH, UDPLITE, ALL
type Libvirt::Nwfilter::Protocol::Igmp_esp_ah_udplite_all = Struct[{
    id         => Enum['igmp', 'esp', 'ah', 'udplite', 'all'],
    match      => Optional[Enum['no','yes']],
    srcmacaddr => Optional[String[1]],
    srcmacmask => Optional[String[1]],
    dstmacaddr => Optional[String[1]],
    dstmacmask => Optional[String[1]],
    srcipaddr  => Optional[String[1]],
    srcipmask  => Optional[String[1]],
    dstipaddr  => Optional[String[1]],
    dstipmask  => Optional[String[1]],
    srcipfrom  => Optional[String[1]],
    srcipto    => Optional[String[1]],
    dstipfrom  => Optional[String[1]],
    dstipto    => Optional[String[1]],
    dscp       => Optional[Integer[0,256]],
    comment    => Optional[String[1,256]],
    state      => Optional[String[1]],
    ipset      => Optional[String[1]],
    ipsetflags => Optional[String[1]],
    connlimit-above => Optional[Integer],
}]
